name: Test colcon-ros-bundle
on:
  pull_request:
  schedule:
    - cron: '43 17 * * *'

jobs:
  run_test_suite:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y enchant
        pip3 install -U setuptools==44.0.0 colcon-bundle rosdep
        pip3 install -r requirements_devel.txt
    - name: Run test
      run: python3 -m pytest --cov=colcon_ros_bundle --cov-branch
